name: pi-kiwix-survival

services:
  kiwix-server:
    image: ghcr.io/kiwix/kiwix-tools:latest
    container_name: kiwix-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./zim_data:/data
    command: ["--library", "--monitorLibrary", "--port=8080", "/data/library.xml"]
